### ISSUE TITLE
不好意思，我遇到个github上面的骗子，想请教一下怎么举报项目

### ISSUE THREAD

**Issue by AlbertMihawk** [maskleo/issues#1]
不好意思，我遇到个github上面的骗子，要怎么举报，好像只有针对人的report abuse，如果是针对欺诈项目是怎么举报的，能告诉我么，谢谢

**Comment by maskleo** [comment]
> 不好意思，我遇到个github上面的骗子，要怎么举报，好像只有针对人的report abuse，如果是针对欺诈项目是怎么举报的，能告诉我么，谢谢

https://help.github.com/cn/github/building-a-strong-community/reporting-abuse-or-spam
